import Header from "@/components/layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Tapestry } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const tapestry = Tapestry({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Learn Tailwind Css Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
